[package]
name = "tit"
version = "0.1.0"
authors = ["Thom Wright <thom.wright@candide.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = "0.1.2"
